import { AppIcon } from "appicon.slint";

export struct AppIconModel { 
    name: string,
    image: image,
}

export component AppIconList inherits Flickable {
    in property <length> icon-size;
    in property <[AppIconModel]> model;

    property <length> item-size: icon-size * 1.3;

    height: item-size;
    viewport-height: item-size;

    selection := Rectangle {
        x: 0px;
        y: 0px;
        width: item-size;
        height: item-size;
        background: gray;
        border-radius: item-size / 20;
        visible: model.length > 0;
    }
    HorizontalLayout {
        for item in model: AppIcon {
            size: item-size;
            icon-size: icon-size;
            icon-name: item.name;
            icon-image: item.image;
        }
    }
}