import { GamepadView } from "gamepad.slint";

// Model Item
export struct GamepadModel {
    name: string,
    status: string,
    charge: int,
}

export component GamepadListView inherits HorizontalLayout { 
    in property <[GamepadModel]> model;

    alignment: end;
    for item[index] in model: GamepadView {
        name: item.name;
        status: item.status;
        charge: item.charge;
    }
}