global GamepadStatusIcon {
    out property <image> charging: @image-url("img/gamepad-status/charging.svg");
    out property <image> discharging: @image-url("img/gamepad-status/discharging.svg");
    out property <image> unknown: @image-url("img/gamepad-status/unknown.svg");
    out property <image> wired: @image-url("img/gamepad-status/wired.svg");
}

export enum GamepadStatus {
    Wired,
    Discharging,
    Charging,
    Unknown
}

// View Components
component Label inherits Text {
    color: white;
    font-size: self.height * 0.6;
    font-family: "Ubuntu";
    font-weight: 700;
    vertical-alignment: center;
    horizontal-alignment: right;
}

component Icon inherits Image {
    in property <length> size;
    width: size;
    height: size;
}

// View
export component Gamepad inherits Rectangle {
    in property <string> name;
    in property <GamepadStatus> status;
    in property <int> charge;

    property <length> spacing: self.height / 4;

    background: #00000040;
    border-radius: root.spacing;

    HorizontalLayout {
        spacing: root.spacing;
        padding-left: root.spacing;
        padding-right: root.spacing;

        Icon {
            size: root.height;
            source: @image-url("img/gamepad.svg");
        }
        Label {
            text: name;
        }
        if isChargeVisible(status): Label {
            text: "| " + charge + "%";
        }
        if status != GamepadStatus.Wired: Icon {
            size: root.height;
            source: getStatusIcon(status);
        }
    }

    function isChargeVisible(status: GamepadStatus) -> bool {
        if (status == GamepadStatus.Charging || status == GamepadStatus.Discharging) {
            return true;
        }

        return false;
    }

    function getStatusIcon(status: GamepadStatus) -> image {
        if (status == GamepadStatus.Wired) {
            return GamepadStatusIcon.wired;
        }

        if (status == GamepadStatus.Discharging) {
            return GamepadStatusIcon.discharging;
        }

        if (status == GamepadStatus.Charging) {
            return GamepadStatusIcon.charging;
        }
        
        return GamepadStatusIcon.unknown;
    }
}