import { Gamepad, GamepadStatus } from "gamepad.slint";

// Model Item
export struct GamepadModel {
    name: string,
    status: GamepadStatus,
    charge: int,
}

export component GamepadList inherits HorizontalLayout { 
    in property <[GamepadModel]> model;

    spacing: self.height / 16;
    padding-left: self.spacing;
    padding-right: self.spacing;

    for item[index] in model: Gamepad {
        name: item.name;
        status: item.status;
        charge: item.charge;
    }
}