import { GamepadModel, GamepadList } from "gamepad-list.slint";
import { AppIconModel, AppIconList } from "appicon-list.slint";

export component MainWindow inherits Window {
    in property <[GamepadModel]> model <=> gamepad-list.model;
    in property <string> clock_text <=> clock.text;

    preferred-width: 800px;
    preferred-height: 600px;

    VerticalLayout {
        alignment: stretch;

        gamepad-list := GamepadList {
            height: 32px;
            alignment: start;
        }

        clock := Text {
            text: "00:00";
            //color: white;
            font-family: "Ubuntu";
            font-size: 270px;
            font-weight: 500;
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            app-list := AppIconList {
                icon-size: 128px;
                model: [
                    {name: "Foo 1", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    {name: "Foo 2", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    {name: "Foo 3", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                    // {name: "Foo 4", image: @image-url("/usr/share/icons/hicolor/256x256/apps/kodi.png")},
                ];
            }
        }

        spacer := Rectangle {
            height: app-list.height / 2;
        }
    }
    
}