export global Style {
    out property <string> default-font-family: "Ubuntu";
    out property <int> default-font-weight: 550;
    out property <color> default-bg-color: #166dbb;
    out property <color> default-panel-color: #00000040;
    out property <color> default-text-color: #ffffff;

    in property <string> font-family: default-font-family;
    in property <int> font-weight: default-font-weight;
    in property <color> bg-color: default-bg-color;
    in property <color> panel-color: default-panel-color;
    in property <color> text-color: default-text-color;
}
